@url = http://localhost:5000
@reservationId = 225e8476-f02c-4c37-b15a-be8ae6e23e2d
@parkingSpotId = 00000000-0000-0000-0000-000000000001

###
GET {{url}}/reservations

###
GET {{url}}/reservations/{{reservationId}}

###
POST {{url}}/reservations/vehicle
Content-Type: application/json

{
    "parkingSpotId": "{{parkingSpotId}}",
    "employeeName": "John1 Doe",
    "licensePlate": "XYZ123",
    "date": "2022-10-01"
}

###
POST {{url}}/reservations/cleaning
Content-Type: application/json

{
    "date": "2022-10-01"
}

###
PUT {{url}}/reservations/{{reservationId}}
Content-Type: application/json

{
    "licensePlate": "XYZ123U"
}

###
DELETE {{url}}/reservations/{{reservationId}}